site_name: 'UPPMAX: Singularity workshop'
repo_url: https://github.com/pmitev/UPPMAX-Singularity-workshop
nav:
  - Home: index.md
  - How to install: installation.md
  - Building remotely: remote_builder.md
  - Building with --fakeroot: fakeroot.md
  - First steps: 
    - Building a container: build_container.md
    - Build own container: own_container.md
    - Running Singularity container: running_singularity.md
    - Running containrs from online repositories: remote_repositories.md
  - Exercises:
    - Real-life example: exercise_01.md
    - Inspect containers: inspect.md
    - Upload to Sylabs container library: exercise_02.md
    - VSCode in Singularity: exercise_04.md
  - Goods and bads: goods_bads.md
  - UPPMAX in a can: uppmax_in_a_can.md 
  - About: about.md
theme:
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  name: material
  custom_dir: overrides
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - footnotes
  - attr_list
  - def_list
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
site_url: https://pmitev.github.io/UPPMAX-Singularity-workshop/
google_analytics:
  - 268147891
  - auto
